/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Fix export button and save": "修复导出按钮和保存",
    "ENABLED": "启用",
    "Export to file": "导出为文件",
    "Import clipboard": "从剪贴板导入",
    "Import file": "从文件导入",
    "DISABLED": "禁用",
    "Experience": "经验值",
    ", and": ", 和",
    "A game prototype by": "一个游戏原型来自",
    "All images in this prototype are AI generated. If you would rather not see them, turn on blurring.": "这个原型中的所有图像都是人工智能生成的。如果你不想看到他们，打开模糊。",
    "and": "和",
    "and brought to life using": "并通过使用赋予生命",
    "Buy": "购买",
    "Credits": "鸣谢",
    "Fight": "战斗",
    "GitHub": "GitHub",
    "Map": "地图",
    "Reset data": "重置数据",
    "Help I'm stuck": "救命，我被卡住了",
    "is assembled at a total cost of": "组建的总成本",
    "Unnamed Band": "无名队伍",
    "Unlocks all characters. Definitely spoils the game.": "解锁所有角色。绝对是毁了游戏。",
    "Unlock everything": "解锁全部",
    "Treasures and adventure await inside.": "宝藏和冒险在里面等着你。",
    "to hire more members.": "雇佣更多的成员。",
    "Navigation": "导航",
    "If you want to skip ahead, you can cheat and double your fruit.": "如果你想跳过这一步，你可以作弊，让你的水果加倍。",
    "Grenze Gotisch": "Grenze Gotisch",
    "Enter the Dungeon": "进入地牢",
    ". All images were created with": "。所有图像都创建自",
    ". See the source code on": ". 查看源码在",
    ". The fonts used are": ". 使用的字体是",
    "ands": "ands",
    "Currently fighting:": "当前战斗:",
    "Blur images": "模糊图片",
    "damage": "伤害",
    "Enable online features": "启用在线功能",
    "Leave the dungeon and return to safety.": "离开地牢，回到安全的地方。",
    "Retreat": "撤退",
    "The": "",
    "Throw away all your progress and start over.": "丢掉你所有的进度，重新开始。",
    "Wooden Stick": "木棍",
    "Whack it with a stick.": "用棍子敲它。",
    "Wild Slime": "野生史莱姆",
    "Band": "队伍",
    "Defeated! You gained": "已击败! 你获得了",
    "Developer tools": "开发者工具",
    "Continue exploring the dungeon.": "继续探索地牢。",
    "FLUX Style Shaping": "通量风格塑造",
    "Keep going": "继续前进",
    "You start over, but keep the": "你重新开始，但保留",
    "You cannot change your band now. The dungeon is dangerous. Retreat to a safe place to make changes.": "你现在不能更改你的队伍。地牢很危险。退到一个安全的地方才能更改。",
    "You share persistent progress, and everyone can go on dungeon runs independently.": "你可以分享持续的进展，每个人都可以独立地在地牢运行。",
    "you've collected. Spend it on your band!": "你已经收集的。把钱花在你的队伍上吧！",
    "When enabled, you can play Bands & Bonds with friends.": "启用后，你可以和朋友一起玩 组队与冒险。",
    "provides the database for the online features. Written in TypeScript using": "提供在线特性的数据库。在TypeScript中使用",
    ". The map was drawn in": "。地图已经画好了",
    ", leaving you with": "，留给你的是",
    "for": "需要",
    "Stick Master": "棍棒大师",
    "Stick Master is a humble explorer. While wandering the forest, they came upon the ruins of a long-lost castle.\nAt the lowest level, they discovered the entrance to the dungeon.": "棍棒大师是一位谦逊的探险家。在森林里游荡时，他们发现了一座失传已久的城堡的废墟。在最底层，他们发现了地牢的入口。",
    "Rewards when defeated:": "击杀奖励:",
    "onds": "onds",
    "Disable online features": "禁用在线功能",
    "Share this link with a friend to let them join your team.": "与朋友分享这个链接，让他们加入你的团队。",
    "Unblur images": "取消模糊图片",
    "Click again if you are sure.": "如果确定，请再次点击。",
    "Prisoner found": "发现囚犯",
    "Release the poor creature.": "放了这个可怜的家伙。",
    "Rescue prisoner": "拯救囚犯",
    "You see a hooded figure in a cage. Will you let them out?": "你看到一个戴着兜帽的人被关在笼子里。你会放他们出来吗？",
    "Go straight": "直走",
    "Camping": "野营",
    "A heavy door stands in front of you. It is barred from this side. You can open it if you dare.": "你面前有一扇沉重的门。它被禁止从这边进入。如果你有胆量，你可以打开它。",
    "A quiet corridor leads into an ill-maintained part of the dungeon.": "一条安静的走廊通向地牢里一个维修不善的地方。",
    ". And I think sometimes that's for the best.": "。我认为有时候这是最好的。",
    "My staff is": "我的法杖",
    "Retreat to make changes to the band": "撤退以对队伍进行更改",
    "Turn right": "右转",
    "Turn left": "左转",
    "You see a door to the left. It hangs ajar, and you can hear the sound of movement from beyond it.": "你看到左边有一扇门。它半开着，你可以听到从它后面传来的动静。",
    "Try swapping me for Lamplighter. You can do so on the Band page.": "把我换成点灯人试试。可以在队伍页面进行操作。",
    "不锋利": "不太锋利",
    "Bandlings": "绑带",
    "Currently fighting the": "当前对抗",
    "Defeated": "击败",
    "enemies! You gained": "敌人! 你获得了",
    "Victory!": "胜利!",
    "Her sweet melody doubles the damage dealt by friends standing next to her.": "她甜美的旋律使站在她旁边的朋友造成的伤害加倍。",
    "is rescued!": "获救了！",
    "The Silent Song": "无声之歌",
    "Click again to confirm.": "再次点击以确认。",
    "Click me to select me": "点击我以选择我",
    "Lamplighter": "点灯人",
    "You can change your band here. Tap members to select or remove them. Tap empty spaces to move or add the selected member.": "你可以在这里换队伍。轻按成员，选择或删除成员。轻按空格移动或添加所选成员。",
    "Buy more": "购买更多",
    "Click here to add The Silent Song to the band": "点击这里将 无声之歌 加入队伍",
    "Click me again to remove me from the band": "再次点击我将我从队伍中移除",
    "Illuminate": "照亮",
    "Lamplighter lights up the tiles around it, letting you expand your band.": "点灯器照亮了周围的地块，可以扩大你的队伍。",
    "Select someone below to add them to the band": "选择下面的人将他们添加到队伍",
    "Shines a light on the battlefield, hurting the eyes accustomed to darkness.": "把一束光洒在战场上，刺痛习惯了黑暗的眼睛。",
    "to afford adding Lamplighter to the band": "才能把“点灯人”加入队伍",
    "Click here to add Lamplighter to the band": "点击这里添加 点灯人 到队伍",
    "Animated Skeleton": "动画骷髅",
    "Poison Crow": "毒药乌鸦",
    "blunt": "钝器",
    "Thick Door": "厚重的门",
    "A warrior equipped with metal armor and weapons expertly crafted in the forges of the Friendship Mountain.": "一名装备着金属盔甲和武器的战士，在友谊山的熔炉中精心制作。",
    "armor": "护甲",
    "Dead Gladiator": "死去的角斗士",
    "Friend of Metal": "金属之友",
    "I have observed that": "我已经观察到",
    "is subtracted from incoming damage.": "从受到的伤害中扣除。",
    "nothing": "什么都没有",
    "page. You can also use this to share progress between multiple devices.": "页。您还可以使用它在多个设备之间共享进度。",
    "This game can be played with friends online. You go on adventures individually and share the persistent progress. Check the": "这个游戏可以和朋友在线玩。你们各自冒险，分享持续的进步。检查",
    "This game is not meant to be slow. If it feels slow, try a different band composition or go in a different direction.": "这个游戏并不意味着慢。如果感觉节奏缓慢，可以尝试不同的队伍组合或朝着不同的方向前进。",
    "Your friend plays a wonderful folk song, very quietly.": "你的朋友弹奏了一首美妙的民歌，非常轻柔。",
    "At least we have enough": "至少我们有足够的",
    "now.": "现在。",
    "to buy more": "去购买更多",
    "You rescued Friend of Metal here earlier. You stop to recover your strength.": "你之前在这里救了金属之友。你停下来恢复你的力量。",
    "Steel Jab": "钢刺",
    "A finely crafted sword in the hands of a Friend of Metal.": "金属之友手中的一把精雕细琢的剑。",
    "a button to keep repeating an attack.": "一个按钮以继续重复攻击。",
    "hold": "按下",
    "You can": "你可以",
    "Good thing I brought a lamp. This must be one of the darkest dungeons I've seen.": "幸好我带了一盏灯。这一定是我见过的最黑暗的地牢之一了。",
    "Did you know you can": "你知道吗你现在可以",
    "move": "移动",
    "band members without removing and re-adding them? One click to select, another click to move. Like my grandma always said.": "不删除和重新添加队伍成员吗？点击一次选择，再点击一次移动。就像我奶奶常说的。",
    "A master of the culinary arts, Dark Chef fights by poisoning the enemies.\nThe only way to defend against his attacks is to dodge them or wear layers of heavy armor.": "暗黑料理人是烹饪大师，通过给敌人下毒来战斗。抵御他攻击的唯一方法就是躲避，或者穿上厚厚的盔甲。",
    "Damage over time.": "随着时间的推移。",
    "Dark Chef": "黑暗料理人",
    "Exit the arena to the left. Wails of prisoners echo from the corridor.": "离开竞技场向左走。囚犯的哀号声在走廊里回响。",
    "Exit the arena to the right. The air from the corridor carries the aroma of growth and decay.": "从竞技场右边出来。走廊的空气中弥漫着生长与腐烂的气息。",
    "Lobster Daddy": "龙虾老爹",
    "Poison Strike": "中毒",
    "An expert Anvilomancer can upgrade your weapons in the midst of battle.\nUpgrades are mostly lost when leaving the dungeon.\nThe starting weapon level is the square root of the highest level achieved.": "专家级的弓术士可以在战斗中升级你的武器。离开地下城时，大部分升级会丢失。起始武器等级是达到的最高等级的平方根。",
    "Anvilomancer": "弓术士",
    "Continue left, where the air is cooler.": "继续往左边走，那里的空气更凉爽。",
    "Continue right, where the air is warmer.": "继续往右走，那里的空气比较暖和。",
    "Frozen Centurion": "冰封百夫长",
    "Frozen Centurion dodges attacks that take longer\n      than": "冰封百夫长闪避攻击的时间超过\n",
    "bite attacks": "叮咬攻击",
    "light attacks": "雷电攻击",
    "ice attacks": "寒冰攻击",
    "The Trollish Maiden heals quickly.": "巨魔少女的恢复速度很快。",
    "Trollish Maiden": "巨魔少女",
    "Forge": "锻造",
    "Increases the level of all weapons. (Currently": "提高所有武器的等级。(当前",
    "Geckalog": "壁虎",
    "You rescued Anvilomancer here earlier. You stop to recover your strength.": "你之前在这里救了一个弓术士。你停下来恢复你的力量。",
    "A master of navigation, Wayfinder will guide your band through the dark corridors of the dungeon.\nJust point to your destination on the map to get started.\nTo repeat the run after reaching the destination, place Wayfinder at the front of your band.": "一个导航大师，探路者将引导你的队伍通过地牢的黑暗走廊。只要在地图上指出你的目的地就可以开始了。\n若要在到达目的地后重复运行，请将探路者放置在队伍前方。",
    "In the Landas Deserts the mages punish loud people by turning their bodies into water.\nThe Eighth Swimmer was one of these unlucky people. Imagine walking among thirsty people\neveryday with a body made of water.": "在兰达斯沙漠中，法师会把大声喧哗的人的身体变成水来惩罚他们。第八名游泳者就是这些不幸的人之一。想象一下，每天带着一个由水构成的身体在干渴的人群中行走。",
    "HP": "生命值",
    "People who shed all their fears and worries can become Kins of Pump. They still love others,\nbut never worry or care about their wellbeing. They are free to pursue their desires without shame.": "那些摆脱了所有恐惧和担忧的人可以成为“水泵之王”。他们仍然爱别人，但从不担心或关心别人的幸福。他们可以自由地追求自己的欲望而不感到羞耻。",
    "Shapeshifters live in the shadows and avoid any chance of being exposed. Except for the Smiling Pilot,\nwho took on the shape of Carl the Twelfth, king of the Froglands. Nobody is sure how long this\nruse lasted, and which of the decrees were written by the Smiling Pilot.": "变形人生活在阴影中，避免任何暴露的机会。除了那个微笑的领航员，他的外形是卡尔十二世，弗罗腺体的国王。没有人知道这场战争持续了多久，也没有人知道哪些法令是微笑的飞行员写的。",
    "The Kin you found in the dungeon came here to search for treasure. They do not help out with fighting\nor taking care of the band. They are great at finding gold, though. All gold finds are doubled.": "你在地牢里找到的亲戚是来这里寻宝的。他们既不帮忙战斗，\n也不照顾队伍。不过，他们很擅长找金子。所有发现的黄金都翻了一番。",
    "The Xaranthian Empire is said to be ruled by wise engineers who built powerful machines to ease their work.\nBut building such machines is hard work too, so the Xarantians built factories to produce mechanical turtles\nthat can build machines that can deploy other machines that can grow further machines.": "据说萨兰提帝国是由聪明的工程师统治的，他们建造了强大的机器来减轻他们的工作。但是制造这样的机器也是一项艰苦的工作，所以萨兰提人建造了工厂来生产机械龟，这些机械龟可以制造出可以部署其他机器的机器，这些机器可以生产出更多的机器。",
    "Zaktar Kadoque is an explorer from another world. He was not trapped in his cage at all,\nrather he was examining it. He loves this dungeon and is very happy to have met your band.\nHe is particularly interested in the fruit you're holding.": "扎克塔·卡多克是来自另一个世界的探险家。他根本没有被困在笼子里，而是在检查笼子。他喜欢这个地牢，很高兴见到你的队伍。他对你拿着的水果特别感兴趣。",
    "A collector of unusual pets. Mongreler can capture weakened enemies and deploy them on the battlefield.": "收集不寻常宠物的人。杂种狗可以捕获虚弱的敌人并将他们部署在战场上。",
    "A deceptively slow attack that cannot be dodged.": "一个无法躲避的缓慢攻击。",
    "A flight of small magical blades timed perfectly to find the weak spots of the enemy.": "一群神奇的小刀片精确地找到了敌人的弱点。",
    "A frozen warrior. Legends say his attacks will kill any foe, but each swing takes a thousand years.": "冰封战士。传说他的攻击可以杀死任何敌人，但每一挥都需要一千年。",
    "A thief, wanted in all the thirty kingdoms. Yet nobody is able to give an accurate description of him.": "一个小偷，三十国都在通缉他。然而，没有人能准确地描述他。",
    "A very cold blade with a very sharp edge.": "一把非常冷的刀刃，刀刃非常锋利。",
    "A whirlwind of sharp blades ravages the battlefield.": "利刃的旋风蹂躏了战场。",
    "A wizard of speed, Kit Flash can speed up the abilities of every member of the band.": "作为一名速度巫师，装备闪光 可以加速队伍中每个成员的能力。",
    "Artifact Seeker": "神器搜寻者",
    "As a member of your band, he copies the attacks of the two friends to his left and right.": "作为你的队伍成员，他复制了两个朋友的攻击到他的左边和右边。",
    "Azrekta": "阿兹列克塔",
    "Azrekta bedevils her friends and foes. Her friends become more powerful versions of themselves.\nHer enemies become ethereal, making them challenging to hit.": "阿兹列克塔使她的朋友和敌人都陷入困境。她的朋友们变成了更强大的自己。她的敌人变得虚无缥缈，使他们难以击中。",
    "Battle Rhythm": "战斗节奏",
    "Bayla": "贝拉",
    "Bayla is a master of movement. She can change her position in the middle of a fight to best target the weak spots\nof her enemies. She's great friends with the Desert Rabbit.": "贝拉是个动作大师。她可以在战斗中改变自己的位置，以最好地瞄准弱点而不是敌人。她是沙漠兔的好朋友。",
    "Buy a fruit sapling at the Hedge Market.": "在对冲市场买一棵树苗。",
    "Buy a piece of fruit at the Hedge Market.": "在对冲市场买一块水果。",
    "Buy Fruit": "购买水果",
    "Buy Sapling": "购买树苗",
    "Chago": "查戈",
    "Chago's Chamber": "查戈的房间",
    "Chased by assassins from the Froglands, the Smiling Pilot eventually took refuge in this treacherous dungeon.": "在弗罗腺体的刺客的追捕下，微笑飞行员最终在这个危险的地牢中避难。",
    "Claws & Thorns": "利爪和荆棘",
    "Coldblade": "寒刃",
    "Construct a mechanical grower.": "建造一个机械种植器。",
    "Construct Grower": "建筑种植者",
    "Core Diver": "核心潜水员",
    "Corridor of Illusions": "幻影走廊",
    "Corrupted Bounty Hunter": "堕落的赏金猎人",
    "Crystal Man": "水晶人",
    "Decay Manifest": "衰变清单",
    "Defensive Installation": "防御装置",
    "Desert Rabbit": "沙漠兔子",
    "Do you have too much fruit? Zaktar Kadoque can eat the leftovers.": "你是不是水果吃多了？扎克塔·卡多克可以吃剩饭。",
    "dodge": "闪避",
    "Door of Loathing": "厌恶之门",
    "Dragonfly Agaric": "蜻蜓木耳",
    "Dryfin Carp": "干鳍鲤鱼",
    "Eat Fruit": "吃水果",
    "Eighth Swimmer": "第八个游泳运动员",
    "Enantiomers": "对映体",
    "Flood": "洪水",
    "Food Mimic": "食物模拟",
    "Fortified Door": "坚固的门",
    "Frog Assassin": "青蛙杀手",
    "Glacial Strike": "冰川冲击",
    "Glass Dragon": "玻璃龙",
    "Gnollish Ambassador": "土狼大使",
    "Golden Chest": "黄金宝箱",
    "Hedge Lost": "对冲市场",
    "Hedge Lost is the only trader in the Hedge Market who is not originally a shrew.": "在对冲市场中，唯一的交易者最初不是一个泼妇。",
    "Hiber Conduit": "希伯管道",
    "Hippogryph": "鹰头兽",
    "Hopanoids": "蛇蛛",
    "Jaw Maw Maw": "下巴奶奶",
    "Kevin": "凯文",
    "Kevin is not so much a person as a phenomenon. When Kevin is present, all enemies are vulnerable to fire.": "凯文与其说是一个人，不如说是一种现象。当凯文在场时，所有敌人都很容易受到攻击。",
    "Kin of Pump": "泵的亲戚",
    "King of Tadpoles": "蝌蚪之王",
    "Kit Flash": "装备闪光",
    "Knight of Claws": "魔爪骑士",
    "Landas Wizard": "兰达斯巫师",
    "Lior the Weaver": "织女莉奥",
    "Lord of Gears": "装备之王",
    "Lost Swimmer": "迷路的游泳者",
    "Master of Doors": "主人的门",
    "Mongreler": "杂种狗",
    "Only works with fruit acquired on this run.": "只适用于这次旅行中获得的水果。",
    "Pecquer": "佩克",
    "Pecquer is a veteran mercenary from the thirty kingdoms. The warriors he fought besides sing songs of his bravery.": "佩克是来自三十国的资深雇佣兵。与他作战的战士们除了歌颂他的英勇外，还歌颂他的英勇。",
    "Pecquer leads the band fearlessly past the enemy.": "佩克带领队伍无畏地越过敌人。",
    "Potato Golem": "土豆魔像",
    "Power Crystal": "动力晶体",
    "Pur Lion": "普尔狮子",
    "regeneration/s": "回复/秒",
    "Royal Fruitbearer": "皇家水果使者",
    "Running Start": "运行启动",
    "Scaffold Sorcery": "刑台魔法",
    "Skelemasterion": "猎骨狂狮",
    "Skeletron": "骷髅怪",
    "Skyrmions": "天空魔王",
    "Smiling Pilot": "微笑的飞行员",
    "Smother Mother": "窒息的母亲",
    "Snatch": "抢夺",
    "Sneak Past": "潜行过去",
    "Speed up all combat abilities. (Currently": "加速所有战斗技能。(当前",
    "Steals a piece of gold.": "偷走了一块金子。",
    "Striped Horror": "条纹恐怖",
    "Sullen Bearer": "阴沉的信使",
    "Tenebra": "特涅布拉",
    "The Desert Rabbit grew up fighting gigantic enemies. He has developed a keen sense for their weaknesses.": "沙漠兔从小就和巨大的敌人战斗。他对他们的弱点产生了敏锐的感觉。",
    "The Final Warden": "最后的监狱长",
    "The King's": "国王的",
    "The Lord of Gears is a master of automation. The band members next to him need not do anything.\nTheir abilities will be activated automatically.": "《装备之王》是自动化的大师。他旁边的队伍成员不需要做任何事。他们的能力将被自动激活。",
    "The Shroud": "裹尸布",
    "The Xaranthian factories in turn are built by Xaranthian Constructors. This one has never seen\na Xaranthian person, and neither has anyone else in your band.": "萨兰提亚的工厂依次由萨兰提亚的建造者建造。这个人从没见过任何萨兰提人，你们队伍里的其他人也没见过。",
    "They found refuge in this dungeon and now in your band.": "他们在地牢里找到了避难所现在又投靠了你的队伍。",
    "Tombstone of the Forgotten": "被遗忘者墓碑",
    "Tosyl Rose": "托西玫瑰",
    "Trained as an assassin, the Knight of Claws works best on his own. His power doubles for every empty space next to him.": "作为一名训练有素的刺客，魔爪骑士单干效果最好。他身边每有一个空位，他的力量就会加倍。",
    "Unwelcoming Glade": "不友好的空地",
    "Uses left:": "剩余使用次数：",
    "Wands from the Depths": "来自深渊的魔杖",
    "Wayfinder": "寻路者",
    "Web of Power": "力量之网",
    "Will-o-Wasp": "黄蜂意志",
    "With the Desert Rabbit in your band, you will see the weaknesses of enemies and the right attacks will deal double damage.": "有了沙漠兔在你的队伍，你会看到敌人的弱点，正确的攻击将造成双倍的伤害。",
    "With the Royal Fruitbearer in your band, whenever you find fruit in the dungeon, every member of the band gives a piece to every other member.": "在你的队伍中有了皇家水果采摘者，当你在地牢中找到水果时，队伍的每个成员都会给其他成员一个水果。",
    "With Wayfinder in your band, you can replace members of your band at campfires.\nNow that Wayfinder is free, you can see more details on the map.": "寻路者在你的队伍中，你可以在篝火上替换你的队伍成员。现在寻路者是免费的，你可以在地图上看到更多细节。",
    "Xaranthian Construct": "萨兰提亚构造",
    "Xaranthian Constructor": "萨兰提亚建造者",
    "Zakatrixos": "扎克特里克斯",
    "Zaktar Kadoque": "扎塔尔·卡多克",
    "attacks from the back": "从后边攻击",
    "attacks from the left": "从左边攻击",
    "attacks from the right": "从右边进攻",
    "attacks from the front": "从正面进攻",
    "Captured Monsters": "捕获的怪物",
    "Cover the enemy in slime.": "用史莱姆覆盖敌人。",
    "Desert Rabbit tells you that Wild Slime is weak to": "沙漠兔子告诉你野生史莱姆很虚弱",
    "Desert Rabbit tells you that Wild Slime was weak to": "沙漠兔子告诉你野生史莱姆很虚弱",
    "fire attacks": "火系攻击",
    "Mongreler wants to capture enemies. Damage is reduced by 99% to avoid killing them.": "杂种狗想要捕获敌人。伤害降低99%以避免杀死他们。",
    "Slobber": "口水",
    "Desert Rabbit tells you that Potato Golem is weak to": "沙漠兔告诉你, 土豆魔像 很虚弱",
    "Desert Rabbit tells you that Potato Golem was weak to": "沙漠兔告诉你, 土豆魔像 很虚弱",
    "Desert Rabbit tells you that Xaranthian Construct was weak to": "沙漠兔告诉你, 萨兰提亚构造 很虚弱",
    "Desert Rabbit tells you that Xaranthian Construct is weak to": "沙漠兔告诉你, 萨兰提亚构造 很虚弱",
    "Desert Rabbit tells you that Will-o-Wasp is weak to": "沙漠兔告诉你, 黄蜂意志 很虚弱",
    "Desert Rabbit tells you that Will-o-Wasp was weak to": "沙漠兔告诉你, 黄蜂意志 很虚弱",
    "Desert Rabbit tells you that Lobster Daddy is weak to": "沙漠兔告诉你, 龙虾老爹 很虚弱",
    "Desert Rabbit tells you that Lobster Daddy was weak to": "沙漠兔告诉你, 龙虾老爹 很虚弱",
    "Desert Rabbit tells you that Glass Dragon is weak to": "沙漠兔告诉你, 玻璃龙 很虚弱",
    "Desert Rabbit tells you that Glass Dragon was weak to": "沙漠兔告诉你, 玻璃龙 很虚弱",
    "Desert Rabbit tells you that Gnollish Ambassador is weak to": "沙漠兔告诉你, 土狼大使 很虚弱",
    "Desert Rabbit tells you that Gnollish Ambassador was weak to": "沙漠兔告诉你, 土狼大使 很虚弱",
    "Desert Rabbit tells you that Dragonfly Agaric is weak to": "沙漠兔告诉你，蜻蜓木耳 很虚弱",
    "Desert Rabbit tells you that Dragonfly Agaric was weak to": "沙漠兔告诉你，蜻蜓木耳 很虚弱",
    "Desert Rabbit tells you that Geckalog is weak to": "沙漠兔告诉你，壁虎很虚弱",
    "Desert Rabbit tells you that Geckalog was weak to": "沙漠兔告诉你，壁虎很虚弱",
    "Desert Rabbit tells you that Frozen Centurion is weak to": "沙漠兔告诉你，冰封百夫长很虚弱",
    "Desert Rabbit tells you that Frozen Centurion was weak to": "沙漠兔告诉你，冰封百夫长很虚弱",
    "Striped Horror dodges attacks that take longer\n      than": "条纹恐怖闪避攻击的时间超过\n",
    "Jaw Maw Maw heals quickly.": "下巴奶奶恢复速度很快。",
    "You rescued Wayfinder here earlier. You stop to recover your strength.": "你之前在这里救了探路者。你停下来恢复你的力量。",
    "Without Azrekta's magic, I have to start my work over each time we enter the dungeon.": "没有阿兹蕾克塔的魔法，我每次进入地牢都得重新开始。",
    "You rescued Desert Rabbit here earlier. You stop to recover your strength.": "你之前在这里救了沙漠兔。你停下来恢复你的力量。",
    "I will take care of fighting. Someone else can handle navigation.": "战斗就交给我吧。其他人可以处理导航。",
    "band members without removing and re-adding them? Bayla can do it even inside the dungeon.": "队伍成员没有删除和重新添加？即使在地牢里，贝拉也能做到。",
    "If Desert Rabbit sees an opening on the left, move me to the left so I can strike!": "如果沙漠兔看到左边有空位，把我移到左边，这样我就可以攻击了！",
    "Dragonfly Agaric is immune to": "蜻蜓木耳免疫",
    "Dragonfly Agaric was immune to": "蜻蜓木耳免疫",
    "poison attacks": "中毒攻击",
    "The spores of the Dragonfly Agaric are toxic to everything but itself.": "蜻蜓木耳的孢子对除了它自己以外的一切都是有毒的。",
    "Artifact Seeker dodges attacks that take longer\n      than": "神器探索者闪避攻击的时间超过\n",
    "blunt attacks": "钝性攻击",
    "Desert Rabbit tells you that Artifact Seeker is weak to": "沙漠兔告诉你，神器探索者很虚弱",
    "Desert Rabbit tells you that Artifact Seeker was weak to": "沙漠兔告诉你，神器探索者很虚弱",
    "Desert Rabbit tells you that Golden Chest is weak to": "沙漠兔告诉你，黄金宝箱很虚弱",
    "water attacks": "水系攻击",
    "You rescued Bayla here earlier. You stop to recover your strength.": "你之前在这里救了贝拉。你停下来恢复你的力量。",
    "Azrekta is truly magical. Time to experiment!": "阿兹蕾克塔真的很神奇。是时候进行实验了！",
    "Wayfinder is placed in the back. Your band will not start over after reaching the destination.": "探路者放置在后面。到达目的地后，您的队伍将不会重新开始。",
    "Dark Lord": "黑暗领主",
    "Stop traveling": "停止旅行",
    "Clockomancer": "时钟术士",
    "Ask Wayfinder to stop for now.": "让探路者暂时停止。",
    "Continue down the corridor.": "继续沿着走廊走。",
    "Leave this twisting corridor through the alcove to the left.": "离开这条蜿蜒的走廊，穿过左边的凹室。",
    "Will-o-Wasp dodges attacks that take longer\n      than": "黄蜂躲避攻击的时间超过\n",
    "You rescued Dark Chef here earlier. You stop to recover your strength.": "你之前在这里救下了黑暗料理人。你停下来恢复你的力量。",
    "You rescued Royal Fruitbearer here earlier. You stop to recover your strength.": "你之前在这里救了皇家水果使者。你停下来恢复体力。",
    "A heavy door to the west. You smell damp earth.": "西面有一扇沉重的门。你闻到了潮湿的泥土味。",
    "Open door": "开门",
    "sharp attacks": "尖锐攻击",
    "Copy invite link": "复制邀请链接",
    "The fruiting bodies of the Decay Manifest regrow as soon as you destroy them.": "腐烂显现的子实体一旦被你摧毁就会重新生长。",
    "The Hippogryph heals quickly.": "鹰头兽恢复速度快。",
    "Download your current game state as a JSON file.": "下载你当前游戏进度存档为JSON格式。",
    "Drop a JSON file here to import your game state.": "拖一个JSON格式存档文件到这里以导入。",
    "Export game state": "导出游戏存档",
    "Import game state": "导入游戏存档",
    ". (Currently": ". (当前",
    "Shapeshifters live in the shadows and avoid any chance of being exposed. Except for the Smiling Wizard,\nwho took on the shape of Carl the Twelfth, king of the Froglands. Nobody is sure how long this\nruse lasted, and which of the decrees were written by the Smiling Wizard.": "变形人生活在阴影中，避免任何暴露的机会。除了微笑的巫师，他变成了卡尔十二世，弗罗腺体的国王。没有人知道这个禁令持续了多久，也没有人知道哪些法令是微笑的巫师写的。",
    "An expert Anvilominator can upgrade your weapons in the midst of battle.\nThe Anvilominator retains upgrades from earlier runs.\nThe starting weapon level is the highest level achieved.": "专家级的反影者可以在战斗中升级你的武器。\n反影者保留了之前的升级版本。\n初始武器等级为已达到的最高等级",
    "In the Landas Deserts the mages punish loud people by turning their bodies into water.\nThe Eighth Swimmer was one of these unlucky souls. Imagine walking among thirsty people\neveryday with a body made of water.": "在兰达斯沙漠中，法师会把大声喧哗的人的身体变成水来惩罚他们。第八名游泳者就是这些不幸的灵魂之一。想象一下，每天带着一个由水构成的身体在干渴的人群中行走。",
    "Buy a": "购买一个",
    "Unforge": "未锻造",
    "Anvilominator": "反影者",
    "A collector of unusual pets. Monster Juggler can capture weakened enemies and deploy them on the battlefield.\nThe captured enemies are kept even when the band retreats.": "收集不寻常宠物的人。怪物杂耍者可以捕获虚弱的敌人并将他们部署到战场上。俘虏的敌人即使撤退也不会被带走。",
    "A frozen warrior. Legends say his attacks will kill any foe, but each swing takes a hundred years.": "冰封战士。传说他的攻击可以杀死任何敌人，但每一击都需要一百年。",
    "A wizard of great speed. Kit Storming can quickly speed up the combat abilities of every member of the band.": "一个速度极快的巫师。装备风暴可以快速加速每个成员的战斗能力。",
    "at the Hedge Market.": "在对冲市场。",
    "Chased by assassins from the Froglands, the Smiling Wizard eventually took refuge in this treacherous dungeon.": "在弗罗腺体的刺客的追捕下，微笑巫师最终躲进了这个危险的地牢。",
    "Damages the armor of the enemy.": "破坏敌人的装甲。",
    "Gear of Lords": "装备领主",
    "Increases the level of all weapons by": "提高所有武器的等级",
    "Kin of Pump doubles the gold found after battles.": "战斗结束后，泵族获得的金币翻倍。",
    "Kit Storming": "装备风暴",
    "Lamperlighter": "点灯器",
    "Monster Juggler": "怪物变戏法的人",
    "Monster Juggler wants to capture enemies. Damage is reduced by 99% to avoid killing them.": "怪物杂耍者想要捕获敌人。伤害降低99%以避免杀死他们。",
    "Pecquer is a veteran mercenary from the thirty kingdoms. The warriors who fought beside him sing songs of his bravery.": "佩克是来自三十国的资深雇佣兵。与他并肩作战的战士们歌颂他的英勇。",
    "Smiling Wizard": "微笑的向导",
    "Standing next to Azrekta, the Smiling Wizard takes her shape and copies her ability.": "微笑法师站在阿兹蕾克塔旁边，取了她的形状并复制了她的能力。",
    "The Gear of Lords is the ultimate master of automation. All abilities will be activated automatically.": "领主装备是自动化的终极大师。所有技能将自动激活。",
    "When you find fruit, every member of the band gives a piece to every other member. (Thanks to the Royal Fruitbearer.)": "当你找到水果时，队伍的每个成员都会给其他成员一块。（感谢皇家水果采摘师。）",
    "The head of the Tosyl warrior disappears in an explosion of sharp petals.\nThen a whirlwind collects all the petals and puts them back together in the shape of a rose. Beautiful and deadly.": "托西尔战士的头在尖锐的花瓣爆炸中消失了。然后一阵旋风把所有的花瓣收集起来，又把它们拼成一朵玫瑰的形状。美丽而致命。",
    "Spider Power": "蜘蛛之力",
    "Tail Whoop": "尾巴大叫",
    "Sting": "刺击",
    "per second.)": "每秒.)",
    "Mimic Fruit": "模拟水果",
    "NOT IMPLEMENTED YET": "尚未实现",
    "Last Croak": "最后一声",
    "Last Flash": "最后一闪",
    "Ivory Stripe": "象牙条纹",
    "is my firewood.": "是我的柴火。",
    "Shatter": "粉碎",
    "Shadow Strike": "暗影突袭",
    "“Master,”": "“主人,”",
    "“Good. It would not fit in our stove anyway.”": "“很好。反正也放不下我们的炉子。”",
    "“I will never finish chopping all this firewood!”": "“这些柴火我永远也劈不完！”",
    "he called,": "他叫道，",
    ".\nHave these chests always been around us?": "．这些箱子一直在我们身边吗？",
    ". And I think sometimes that’s for the best.": "。我认为有时候这是最好的。",
    "A lurching attack that seems easy to defend against. The metal of the blade can be stopped by armor. The evil of its bearer can not.": "似乎很容易抵御的突然袭击。刀刃的金属可以被盔甲阻挡。邪恶的承载者不能。",
    "A powerful claw attack.": "强有力的爪子攻击。",
    "A quick strike of the Geckalog's tail.": "壁虎的尾巴快速一击。",
    "A quick, sharp stab is all that is felt.": "快速而尖锐的刺痛是唯一的感觉。",
    "A vengeful gladiator attacks.": "一个复仇的角斗士进攻了。",
    "A warning, a generous pause, then the ring of a deadly weapon.": "一个警告，一个慷慨的停顿，然后是致命武器的铃声。",
    "A web of Gnollish steel wires strangle the enemy.": "一张格奴利钢丝网扼死了敌人。",
    "Agaric Poison Strike": "木耳毒击",
    "An attack of patience and determination.": "对耐心和决心的攻击",
    "An attack that comes from all directions at once.": "同时来自四面八方的攻击。",
    "and a fulcrum on which to place it, and I shall blow up the world.": "还有一个支点，我要把世界炸掉。",
    "Applies a bone to the head of the enemy.": "在敌人的头上插上一根骨头。",
    "Blades of Revenge": "复仇之刃",
    "Bonetron": "骨波",
    "Buy a fruit sapling at the Hedge Market.\n(Currently": "在对冲市场买一棵小树苗",
    "Cancelion": "取消",
    "Claw Smash": "利爪重击",
    "Damage over time. (Currently": "随着时间的推移。(目前",
    "damage per second.)": "每秒伤害。)",
    "Dance of Petals": "花瓣之舞",
    "Diplomatic Cables": "外交电文",
    "Ebony Stripe": "乌木条纹",
    "Enemy is ethereal due to Azrekta's presence.\n      Attacks will often miss.": "敌人因为阿兹瑞克塔的存在而变得虚无缥缈。\n攻击通常不会命中目标。",
    "Enemy was ethereal due to Azrekta's presence.\n      Attacks have often missed.": "敌人因为阿兹瑞克塔的存在而变得虚无缥缈。\n攻击经常没有命中。",
    "Envelops the enemy in darkness.": "将敌人笼罩在黑暗中。",
    "Fabric of Reality": "现实织物",
    "Finds a chest containing an artifact worth a thousand pieces of": "发现了一个箱子，里面有一件价值一千件的藏物",
    "Fire Xaranthian Cannons": "发射萨兰提安大炮",
    "Frozen Century": "冰冻世纪",
    "Fumes from the underworld cover the battlefield. All life and light is extinguished.": "来自地下世界的烟雾笼罩着战场。所有的生命和光都熄灭了。",
    "Give me enough": "给我足够的",
    "Grim Strike": "冷酷打击",
    "Healing Factor": "治疗因子",
    "Hibernate": "冬眠",
    "Hidden in Skelemasterion's lair is a stairway leading to the second level of the dungeon.": "在骷髅首领的巢穴中隐藏着一条通往地下城第二层的楼梯。",
    "Hippograb": "海马",
    "Hire a famous assassin.": "雇佣一个著名的刺客。",
    "Jaw Maw Maw can restore anyone to full health, not just herself.": "颚奶奶可以让任何人恢复健康，而不仅仅是她自己。",
    "Knights from beyond the tomb lay waste to your enemies.": "从坟墓那边来的骑士将你的敌人消灭。",
    "Lior the Weaver dodges attacks that take longer\n      than": "或者织女躲避攻击的时间比",
    "Magma Vortex": "岩浆漩涡",
    "Pipes filled with sub-zero liquid coil around the target.": "装有零度以下液体的管子绕在目标周围。",
    "Pushes time forward.": "推动时间向前。",
    "Recruit Tadpole": "招募蝌蚪",
    "Release Hopanoids": "释放蛇蛛",
    "Releasing the Hopanoids will give you a rush of speed.": "释放蛇蛛会让你加速。",
    "Reveal Skelemasterion's Stairway": "打开骷髅座的楼梯",
    "saplings producing": "树苗生产",
    "Seek Artifact": "寻找神器",
    "Shroud of Darkness": "黑暗裹尸布",
    "Skelemasterion defeats the opponent. Skelemasterion is lost in the process.": "骷髅师击败对手。在这个过程中，骷髅王丢失了。",
    "Slows down time.": "减慢时间。",
    "Smother": "窒息者",
    "Sometimes I feel like": "有时候我觉得",
    "Sounds like thunder, looks like lightning bolts flying straight at the target.": "听起来像雷声，看起来像闪电直接飞向目标。",
    "The beast lifts its prey into the air, then smashes them to the ground.": "猛兽把猎物举到空中，然后把它们摔在地上。",
    "The black stripes connect to the darkness of the underworld.": "黑色的条纹让人联想到冥界的黑暗。",
    "The Core Diver floods the area with magma that pulls down your enemies.": "核心潜水员用岩浆淹没这个区域，把你的敌人拉下来。",
    "The Dark Lord never misses.": "黑魔王从不失手。",
    "The deadly poison of the Dragonfly Agaric causes great damage over time.": "随着时间的推移，蜻蜓木耳的致命毒药会造成巨大的伤害。",
    "The Enantiomers cancel each other out in a final burst that increases your speed.": "对映体在最后的爆发中相互抵消，从而提高反应速度。",
    "The Final Warning": "最后警告",
    "The Food Mimic permanently turns into a large amount of": "食物模拟物会永久地变成大量的",
    "The Forgotten Siege": "被遗忘的围攻",
    "The king sends a tadpole to battle.": "国王派一只蝌蚪去打仗。",
    "The master replied,": "大师回答说：",
    "The old master sent his apprentice outside to chop firewood.\nThe apprentice looked up at the great mound of firewood and despaired.": "老师傅派他的徒弟出去砍柴。学徒抬头望着那一大堆柴火，感到绝望。",
    "The quick and painful sting of a wasp.": "黄蜂快速而痛苦的刺。",
    "The repairs are expensive.": "修理费很贵。",
    "The white stripes connect to the light of the heavens.": "白色的条纹与天空的光芒相连。",
    "This is the end of the current content. Congratulations and thanks for playing!": "这是当前内容的结束。恭喜你，谢谢你的参与！",
    "Time Burp": "时间打嗝",
    "Time Wrap": "时间扭曲",
    "Turn right into a loathsome corridor.": "向右转进入一条恶心的走廊。",
    "Waft of Decay": "腐朽之风",
    "While this ability is active, poisoned enemies lose health twice as fast.": "当此技能激活时，中毒的敌人会以两倍的速度失去生命值。",
    "Enemy was ethereal.\n      Attacks have often missed.": "敌人是虚无的。\n攻击经常没有命中。",
    "Emerald Wand": "翡翠魔杖",
    "For the duration of the spell, Zakatrixos shifts the band into the ethereal plane.\nThis negates the defenses of ethereal enemies.": "在施法期间，扎特里克索斯将手带移至虚界。这就否定了虚界敌人的防御。",
    "Landas Wizard dodges attacks that take longer\n      than": "兰达斯巫师闪避攻击的时间超过\n",
    "Look of Loathing": "厌恶的眼神",
    "One of the Wands from the Depths.": "一根来自深处的魔杖。",
    "Pierce the Veil": "揭开面纱",
    "Release Excitation Energy": "释放激发能",
    "Ruby Wand": "红宝石魔杖",
    "Sapphire Wand": "蓝宝石魔杖",
    "Skyrmion pairing of opposite charges from opposite valleys is favored by both Coulomb and effective Zeeman terms.": "来自相反谷的相反电荷的斯格米子对受到库仑项和有效塞曼项的青睐。",
    "The Door of Loathing taunts the enemy and draws its attacks onto itself.": "憎恨之门嘲弄敌人并将其攻击引到自己身上。",
    "You have to be gentle with monsters. Everyone underestimates their power. It takes tender care and patience to tame them.": "你得对怪物温柔点。每个人都低估了自己的能力。驯服它们需要温柔的呵护和耐心。",
    "I could fight more effectively if I had more space to move.": "如果我有更多的移动空间，我可以更有效地战斗。",
    "I know a creature that was once a moose.": "我认识一只曾经是驼鹿的动物。",
    "This band is always in a hurry.": "这个队伍总是很匆忙。",
    "Good thing I brought a lamp. This must be one of the darkest dungeons I’ve seen.": "还好我带了灯。这一定是我见过的最黑暗的地牢之一了。",
    "ethereal": "飘渺",
    "when I'm not around? That must be so cool!": "当我不在的时候？那一定很酷！",
    "You’re telling me the enemies are not": "你告诉我敌人不",
    "multiple buttons to keep repeating attacks.": "多个按钮，以保持重复攻击。",
    "On mobile you can": "在手机上你可以",
    "I want to catch the": "我想抓住",
    "biggest monster": "最大的怪物",
    "Send Sand": "送沙子",
    "A sandstorm passes through the battlefield.": "一场沙尘暴穿过战场。",
    "You found a small opening leading north.": "你发现了一个通向北方的小缺口。",
    "Enemy is ethereal.\n      Attacks will often miss.": "敌人是虚无的。\n攻击通常不会命中目标。",
    "A lumbering shape of magma stands before you. The Core Diver's surface is continuously shed and renewed by a fiery flow.": "一团笨重的岩浆矗立在你面前。核心潜水员的表面是不断脱落和更新的火热的流动。",
    "Gnollish Ambassador dodges attacks that take longer\n      than": "侏儒大使闪避攻击的时间更长\n",
    "Corridor of Illusions dodges attacks that take longer\n      than": "幻影走廊躲避攻击所需的时间大于",
    "Enantiomers dodge attacks that take longer\n      than": "对映异构体躲避攻击的时间长于\n",
    "Enantiomers were weak to": "对映体弱于",
    "Enemies are ethereal due to Azrekta's presence.\n      Attacks will often miss.": "敌人因为阿兹瑞克塔的存在而变得虚无缥缈。\n攻击通常不会命中目标。",
    "Enemies were ethereal due to Azrekta's presence.\n      Attacks have often missed.": "敌人因为阿兹瑞克塔的存在而变得虚无缥缈。\n攻击经常没有命中。",
    "Frog Assassin dodges attacks that take longer\n      than": "青蛙刺客躲避攻击所需时间大于",
    "Hopanoids dodge attacks that take longer\n      than": "蛇蛛躲避攻击的时间比",
    "Hopanoids were weak to": "蛇蛛弱于",
    "The molten parts of Hiber Conduit freeze to a solid form with little delay.": "海伯管道的熔融部分冻结成固体形式，几乎没有延迟。",
    "The Smother Mother is encased in an armor that must have a melting point beyond anything in our world.": "窒息之母裹着一件盔甲，它的熔点一定比我们这个世界上的任何东西都要高。",
    "The air itself is strained and torn as the colossal form of the Final Warden moves, too fast to track.": "当最终守护者的巨大身躯移动时，空气本身也变得紧张和撕裂，速度太快，无法追踪。",
    "The Final Warden dodges attacks that take longer\n      than": "最后的守护者躲避攻击所需的时间大于",
    "dark attacks": "黑暗攻击",
    "ranged attacks": "远程攻击",
    "This dungeon is barely strong enough to contain the invincible Skelemasterion.": "这个地牢的强度几乎不足以容纳无敌的骷髅怪。",
    "pieces of gold.": "金币。",
    "Steals": "偷取",
    "Larger amounts take longer to steal.": "偷更多的钱需要更长的时间。",
    "Glacial Flame Strike": "冰川火焰打击",
    "A very hot blade with a very sharp edge.": "非常热的刀刃，刀刃非常锋利。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "Daniel Darabos": "Daniel Darabos",
    "Germania One": "Germania One",
    "DungeonScrawl": "DungeonScrawl",
    "Sana": "Sana",
    "Vite": "Vite",
    "Vue.js": "Vue.js",
    "Appwrite": "Appwrite",
    "Bellefair": "Bellefair",
    " & ": " & ",
    "": "",
    "": "",
    "": "",
    "": "",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    ". Last updated on ": ". 最近更新于 ",
    "Desert Rabbit tells you that ": "沙漠兔告诉你 ",
    "You rescued ": "你在这里救了 ",
    " dodges attacks that take longer\n      than": " 躲避攻击的时间超过\n",
    " dodge attacks that take longer\n      than": " 躲避攻击的时间超过\n",
    ". And I think sometimes that’s for the best.": "。我认为有时候这是最好的。",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "Faster attacks have a chance to hit.": "快速攻击有一定几率命中。",
    " is immune to": "免疫",
    " was immune to": "免疫",
    " are weak to": " 虚弱",
    " is weak to": " 虚弱",
    " was weak to": " 虚弱",
    " here earlier. You stop to recover your strength.": "。你停下来恢复你的力量。",
    " Armor": " 护甲",
    " HP": " 生命值",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) ms$/,
    /^([\d\.]+) $/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) × ([\d\.,]+)$/,
    /^([\d\.,]+) × ([\d\.,]+) B$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) second ([\d\.,]+) ms$/, '$1 秒 $2 毫秒'],
    [/^([\d\.,]+) seconds ([\d\.,]+) ms$/, '$1 秒 $2 毫秒'],
    [/^([\d\.,]+) minutes ([\d\.,]+) seconds$/, '$1 分 $2 秒'],
    [/^([\d\.,]+) minute ([\d\.,]+) seconds$/, '$1 分 $2 秒'],
    [/^([\d\.,]+) seconds$/, '$1 秒'],
    [/^([\d\.,]+) second$/, '$1 秒'],
    [/^([\d\.,]+) minutes$/, '$1 分钟'],
    [/^([\d\.,]+) years$/, '$1 年'],
    [/^([\d\.,]+) Armor$/, '$1 护甲'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+)(.+)$/, '$1$2'],
    [/^([\d\.,]+) \/ ([\d\.,]+) Armor$/, '$1 / $2 护甲'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);